version: '3.8'

# Inner Voice Frontend - Docker Compose Configuration
# Run from Chatbot directory: docker-compose -f docker/docker-compose.yml up

services:
  # ==========================================
  # Frontend (React + Vite + Nginx)
  # ==========================================
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: inner-voice-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      # Vite environment variables (prefixed with VITE_)
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:5000}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-}
    networks:
      - inner-voice-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

# ==========================================
# Networks
# ==========================================
networks:
  inner-voice-network:
    driver: bridge
