import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-emerald-100 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-gray-600 hover:text-emerald-600 transition"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-medium">Back to Home</span>
          </button>
          <div className="flex items-center gap-3">
            <img src="/assets/avatars/sheep.svg" alt="Daisy" className="w-6 h-6" />
            <h1 className="text-xl font-bold text-gray-800">Inner Voice</h1>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="bg-white rounded-2xl shadow-lg p-8 md:p-12">
          <h1 className="text-4xl font-bold text-gray-800 mb-4">Terms of Service</h1>
          <p className="text-gray-600 mb-8">
            <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
          </p>

          <p className="text-gray-700 mb-8">
            By using Inner Voice, you agree to these Terms of Service. Please read them carefully.
          </p>

          {/* Service Description */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">1. Service Description</h2>

            <div className="bg-green-50 rounded-lg p-6 border border-green-200 mb-6">
              <h3 className="text-lg font-semibold text-green-900 mb-3">What Inner Voice IS:</h3>
              <ul className="space-y-2 text-gray-700">
                <li>✅ A private AI companion for when you're distressed and don't want friends involved</li>
                <li>✅ A safe space to express feelings without judgment or social consequences</li>
                <li>✅ Available 24/7 when you need support but prefer not to burden others</li>
                <li>✅ A tool for practicing coping strategies and self-reflection in private</li>
                <li>✅ Evidence-based wellness techniques (CBT, breathing exercises, mindfulness)</li>
                <li>✅ A way to process emotions before (or instead of) talking to real people</li>
              </ul>
            </div>

            <div className="bg-red-50 rounded-lg p-6 border border-red-200">
              <h3 className="text-lg font-semibold text-red-900 mb-3">What Inner Voice IS NOT:</h3>
              <ul className="space-y-2 text-gray-700">
                <li>❌ A licensed therapist, counselor, or mental health professional</li>
                <li>❌ A medical device or diagnostic tool</li>
                <li>❌ A replacement for professional mental health care</li>
                <li>❌ A replacement for human friendship or real relationships</li>
                <li>❌ An emergency crisis intervention service</li>
                <li>❌ Capable of providing medical advice or diagnoses</li>
              </ul>
            </div>
          </section>

          {/* Core Philosophy */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">2. Core Philosophy</h2>
            <div className="space-y-3 text-gray-700">
              <p>💡 Inner Voice helps you when you need emotional support but prefer privacy</p>
              <p>💡 We provide a judgment-free space without the social complexities of real relationships</p>
              <p>💡 Our goal is to help you process emotions and develop coping skills</p>
              <p>💡 We encourage professional help for serious concerns and real human connection for long-term wellbeing</p>
            </div>
          </section>

          {/* Limitations of AI */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">3. Limitations of AI</h2>
            <div className="bg-amber-50 rounded-lg p-6 border border-amber-200">
              <ul className="space-y-2 text-gray-700">
                <li>⚠️ AI responses are generated by algorithms and may not always be accurate</li>
                <li>⚠️ AI cannot understand context as well as a human therapist or friend</li>
                <li>⚠️ AI cannot provide the genuine human connection you may ultimately need</li>
                <li>⚠️ AI cannot handle emergencies or crisis situations</li>
                <li>⚠️ AI does not have professional judgment or clinical training</li>
              </ul>
            </div>
          </section>

          {/* Crisis Protocol */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">4. Crisis Situations</h2>
            <div className="bg-red-50 rounded-lg p-6 border border-red-200">
              <p className="text-red-900 font-semibold mb-4">
                If you are experiencing suicidal thoughts, self-harm urges, or a mental health emergency,
                IMMEDIATELY contact:
              </p>
              <div className="space-y-2 text-gray-700">
                <p><strong>🆘 Emergency Services:</strong> 911 (US), 112 (EU), 999 (UK)</p>
                <p><strong>🆘 Suicide Prevention Hotline:</strong> 988 (US), 116 123 (UK - Samaritans)</p>
                <p><strong>🆘 Crisis Text Line:</strong> Text HOME to 741741</p>
                <p><strong>🆘 China Mental Health Hotline:</strong> 400-161-9995</p>
              </div>
              <p className="text-red-800 mt-4 font-medium">
                Inner Voice is NOT equipped to handle crisis situations and will direct you to appropriate resources.
              </p>
            </div>
          </section>

          {/* User Responsibilities */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">5. User Responsibilities</h2>
            <p className="text-gray-700 mb-4"><strong>BY USING INNER VOICE, YOU AGREE TO:</strong></p>
            <ol className="list-decimal list-inside space-y-2 text-gray-700">
              <li>Use the app for private emotional support when you prefer not to involve friends</li>
              <li>Understand that Inner Voice is a COMPANION, not a therapist or replacement for human connection</li>
              <li>NOT rely on the app as a substitute for professional mental health care</li>
              <li>Seek professional help for serious mental health concerns or crises</li>
              <li>NOT use the app for medical emergencies</li>
              <li>Recognize that while we provide privacy, real human relationships remain important</li>
              <li>NOT share content that violates our community guidelines</li>
              <li>NOT attempt to manipulate or abuse the AI systems</li>
              <li>Understand that AI responses are supportive guidance, not professional advice</li>
              <li>Use Inner Voice as a tool to process emotions, not as a replacement for all human interaction</li>
            </ol>
          </section>

          {/* Age Requirements */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">6. Age Requirements</h2>
            <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
              <p className="text-gray-700 mb-3">
                You must be at least <strong>16 years old</strong> to use Inner Voice (18 in some countries).
              </p>
              <p className="text-gray-700">
                If you are under the minimum age, please ask a parent or guardian to create an account on your behalf.
              </p>
              <ul className="mt-3 space-y-1 text-sm text-gray-600">
                <li>• EU Default: 16 years old</li>
                <li>• US (COPPA): 13 years old (parental consent required for 13-17)</li>
                <li>• Some EU countries may require 18+ years old</li>
              </ul>
            </div>
          </section>

          {/* Disclaimer of Warranties */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">7. Disclaimer of Warranties</h2>
            <div className="bg-gray-100 rounded-lg p-6 border border-gray-300">
              <p className="text-gray-700 mb-4">
                Inner Voice is provided <strong>"AS IS"</strong> without warranties of any kind. We do not guarantee that:
              </p>
              <ul className="list-disc list-inside space-y-2 text-gray-700">
                <li>AI responses will be accurate, helpful, or appropriate</li>
                <li>The app will be available without interruption</li>
                <li>Use of the app will improve your mental health</li>
                <li>The app is suitable for your specific situation</li>
              </ul>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">8. Limitation of Liability</h2>
            <div className="bg-gray-100 rounded-lg p-6 border border-gray-300">
              <p className="text-gray-700 mb-4">
                To the maximum extent permitted by law, Inner Voice shall not be liable for:
              </p>
              <ul className="list-disc list-inside space-y-2 text-gray-700">
                <li>Any harm resulting from use or reliance on AI responses</li>
                <li>Decisions made based on app interactions</li>
                <li>Technical failures or data loss</li>
                <li>Missed crisis interventions</li>
              </ul>
              <p className="text-gray-700 mt-4 font-medium">
                Your use of professional mental health services remains your responsibility.
              </p>
            </div>
          </section>

          {/* Privacy */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">9. Privacy & Data Protection</h2>
            <p className="text-gray-700 mb-4">
              Your privacy is critically important to us. Please review our{' '}
              <button
                onClick={() => navigate('/privacy-policy')}
                className="text-emerald-600 font-semibold hover:underline"
              >
                Privacy Policy
              </button>
              {' '}to understand how we collect, use, and protect your data.
            </p>
            <div className="bg-green-50 rounded-lg p-6 border border-green-200">
              <p className="text-gray-700 mb-2"><strong>Key Privacy Commitments:</strong></p>
              <ul className="space-y-1 text-gray-700">
                <li>🔒 Conversations stored for 1 hour only (not permanently saved)</li>
                <li>🔒 We NEVER sell or share your emotional data</li>
                <li>🔒 Full GDPR compliance and user data rights</li>
                <li>🔒 Encrypted in transit and at rest</li>
              </ul>
            </div>
          </section>

          {/* Account Termination */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">10. Account Termination</h2>
            <p className="text-gray-700 mb-3">
              You may delete your account at any time from your account settings. Upon deletion:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-700">
              <li>All your personal data will be permanently deleted within 30 days</li>
              <li>Conversation history (already temporary) will be immediately cleared</li>
              <li>You will lose access to all app features</li>
            </ul>
            <p className="text-gray-700 mt-4">
              We reserve the right to terminate accounts that violate these terms.
            </p>
          </section>

          {/* Changes to Terms */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-700">
              We may update these Terms of Service from time to time. Significant changes will be communicated
              via email or in-app notification. Continued use of the app after changes constitutes acceptance
              of the new terms.
            </p>
          </section>

          {/* Contact */}
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">12. Contact Information</h2>
            <div className="bg-gray-50 rounded-lg p-6">
              <p className="text-gray-700 mb-2"><strong>General Inquiries:</strong> support@innervoice.app</p>
              <p className="text-gray-700 mb-2"><strong>Privacy Questions:</strong> privacy@innervoice.app</p>
              <p className="text-gray-700"><strong>Legal Issues:</strong> legal@innervoice.app</p>
            </div>
          </section>

          {/* Footer */}
          <div className="border-t border-gray-200 pt-8 mt-8">
            <div className="bg-emerald-50 rounded-lg p-6 border border-emerald-200 mb-6">
              <p className="text-gray-700 font-medium">
                <strong>Important Reminder:</strong> Inner Voice is a private companion for emotional support
                when you don't want friends involved. We are NOT a replacement for professional mental health
                care, medical treatment, or human connection.
              </p>
            </div>
            <p className="text-sm text-gray-600 text-center mb-6">
              By clicking "Get Started" or creating an account, you acknowledge that you have read,
              understood, and agree to these Terms of Service.
            </p>
            <div className="text-center">
              <button
                onClick={() => navigate('/')}
                className="px-6 py-3 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition font-medium"
              >
                Return to Home
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
